language: generic
env:
  global:
    - CLI_VERSION=latest
  matrix:
    - BOARD="arduino:samd:mkrnb1500"
before_install:
  - mkdir -p "$HOME/bin"
  - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR="$HOME/bin" sh
  - export PATH=$PATH:$HOME/bin
  - arduino-cli core update-index
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino-cli core install arduino:samd;
    fi
  - buildExampleSketch() { arduino-cli compile --verbose --warnings all --fqbn $BOARD $PWD/examples/$1; }
  - buildExampleToolsSketch() { arduino-cli compile --verbose --warnings all --fqbn $BOARD $PWD/examples/Tools/$1; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - buildExampleSketch GPRSUdpNtpClient
  - buildExampleSketch NBSSLWebClient
  - buildExampleSketch NBWebClient
  - buildExampleSketch ReceiveSMS
  - buildExampleSketch SendSMS
  - buildExampleToolsSketch ChooseRadioAccessTechnology
  - buildExampleToolsSketch NBScanNetworks
  - buildExampleToolsSketch PinManagement
  - buildExampleToolsSketch SerialSARAPassthrough
  - buildExampleToolsSketch TestGPRS
  - buildExampleToolsSketch TestModem
