// Define the repository information in these attributes
:repository-owner: arduino-libraries
:repository-name: MKRNB SARA R410 MQTT Extension 0.1

= {repository-name} Library for Arduino =


This library enables an Arduino MKR NB 1500 board to connect to the internet over a NarrowBand IoT or LTE Cat M1 network.
The Cpt. Holzschnauz extension makes it possible to use the internal MQTT functionality of the SARA R410 modem for convenient MQTT.

MQTT without external mqtt libraries, tcp socket headaches etc. 

Easy & convenient! Let the modem do the sh..!


UNDER CONSTRUCTION!! BETA! NOT FINISHED! CONTRIBUTE IF YOU CAN! Check the example.

Done:
Constructor: Example: NBMqtt mqtt;

getMQTTerror Get the last MQTT error from the modem.Example: mqtt.getMQTTerror();  

setMQTTClientID  Set the MQTT client ID : Use your SIM IMEI. Example: mqtt.setMQTTClientID("352753090834234");  

setMQTTPort(Int): Set the MQTT Port (Normal is 1883, SSL is 8883(not yet implemented). Example:  mqtt.setMQTTPort(1883);  

setMQTTUserPassword(String, String): Set Username / Password for the MQTT broker. Example: mqtt.setMQTTUserPassword("username", "password");  

setMQTTbrokerURL(String): Set the MQTT broker URL (DNS is made automatic). Example: mqtt.setMQTTBrokerURL("public.cloud.shiftr.io");   

setMQTTbrokerIP(String): Set the MQTT broker IP (not necessary in general, provide a broker URL!) Example: setMQTTbrokerIP(84.15.13.144);

setMQTTBrokerConnect(bool): Connect / Disconnect to the MQTT broker. Example: mqtt.setMQTTBrokerConnect(true); to connect, mqtt.setMQTTBrokerConnect(false); to disconnect  

sendMQTTMsg(String, String): Send a MQTT message to a topic. Example: mqtt.sendMQTTMsg("/TestTopic", "TestMessage");  

setMQTTSubscribe(String): Subscribe to a topic. Example: setMQTTSubscribe("TestTopic");  

To do:  

Read out MQTT messages  

Set Timeouts  

Set last will  

Save/restore settings to NV memory
  


== License ==

Copyright (c) 2018 Arduino SA. All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
